#!/bin/sh

## Settings ##
CXX="g++"

CXXFLAGS="-std=c++11 -Wall"

SRC_DIRS="utf8string json gc jit gui main"

INCLUDE_FLAGS="-I /home/yurii/local/include/ -I /usr/include/freetype2 "

DEFINITIONS="-DDEBUG -DUSE_SDL2"

LINKER_FLAGS="-lGL -lGLU -lSDL2 -lpng -lftgl -L /home/yurii/local/lib"




## Code ##
SRC_PREFIX=''
BUILD_DIR=`pwd`

if [ -z $BIN_INSTALL_DIR ]; then
    BIN_INSTALL_DIR='./'
fi

if [ -z $DATA_INSTALL_DIR ]; then
    DATA_INSTALL_DIR='./'
fi

#Set SRC_DIR
if [ ! -z $1 ]; then
    cd $1
    SRC_PREFIX=`pwd`
    cd $BUILD_DIR
fi


#Update include flags
for i in $SRC_DIRS; do
    INCLUDE_FLAGS="$INCLUDE_FLAGS -I $SRC_PREFIX/$i"
done


function target_for_src_dir()
{
    cpp_files=`ls $SRC_PREFIX/$1 | grep .cpp$`
    
    for i in $cpp_files; do
        o_file="`printf $i | sed 's/.cpp/.o/g'`"
        
        printf "$o_file :\n"
        printf "\t@echo 'CXX     $1/$i'\n"
        printf "\t@\$(CXX) -c \$(CXXFLAGS) \$(INCLUDE_FLAGS) \$(DEFINITIONS) \$(SRC_PREFIX)/$1/$i\n"
        printf "\t"; echo "@stat -c %Y \$(SRC_PREFIX)/$1/$i > $1.`printf $i | sed 's/.cpp/.modtime/g'`"
        printf "\n"
        
        all_cpp_files="$all_cpp_files $1/$i"
        all_o_files="$all_o_files $o_file"
    done
}


function makefile_content()
{
    printf "#Generated by genmake.sh script.\n\n"
    
    printf "CXX=$CXX\n"
    printf "CXXFLAGS=$CXXFLAGS\n"
    printf "INCLUDE_FLAGS=$INCLUDE_FLAGS\n"
    printf "DEFINITIONS=$DEFINITIONS\n"
    printf "LINKER_FLAGS=$LINKER_FLAGS\n"
    printf "SRC_PREFIX=$SRC_PREFIX\n"
    printf "\n\n"

    printf "default : check_for_source_updates r64fx"
    printf "\n\n"
    
    for i in $SRC_DIRS; do
        target_for_src_dir $i
    done
    
    printf "r64fx : $all_o_files\n"
    printf "\t@echo 'LD     r64fx'\n"
    printf "\t@$CXX -o r64fx $all_o_files \$(LINKER_FLAGS)\n"
    printf "\n\n"
    
    printf "clean :\n"
    printf "\t@rm -f *.o\n"
    printf "\t@rm -f *.modtime\n"
    printf "\t@rm -f r64fx\n"
    printf "\n\n"
    
    printf "install : r64fx\n"
    printf "\t@echo 'Installing r64fx to $INSTALL_DIR'\n"
    printf "\t@cp r64fx $INSTALL_DIR\n"
    printf "\n\n"
    
    printf "uninstall : r64fx\n"
    printf "\t@echo 'Deleting $INSTALL_DIR/r64fx'\n"
    printf "\t@rm $BIN_INSTALL_DIR/r64fx\n"
    printf "\n\n"
    
    printf "check_for_source_updates:\n"
    printf "\t@$BUILD_DIR/check_source_timestamps.sh"
    printf "\n\n"
    
}


makefile_content > Makefile


echo    "#!/bin/sh"                                                                        >  check_source_timestamps.sh
echo    "#Generated by genmake.sh script."                                                 >> check_source_timestamps.sh
echo    "for i in $all_cpp_files; do"                                                      >> check_source_timestamps.sh
echo    "    EXPECTED_MODTIME=0"                                                           >> check_source_timestamps.sh
echo    "    MODTIME_FILE=\`echo \$i | sed 's/.cpp/.modtime/g' | sed 's/\//./g'\`"         >> check_source_timestamps.sh
echo    "    if [ -a $BUILD_DIR/\$MODTIME_FILE ]; then EXPECTED_MODTIME=\`cat \$MODTIME_FILE\`; fi"   >> check_source_timestamps.sh
echo    "    ACTUAL_MODTIME=\`stat -c %Y $SRC_PREFIX/\$i\`"                                >> check_source_timestamps.sh
echo    "    if [ \$EXPECTED_MODTIME != \$ACTUAL_MODTIME ]; then"                          >> check_source_timestamps.sh
echo    "        TARGET=\`printf \$i | sed 's/.cpp/.o/g'\`"                                >> check_source_timestamps.sh
echo    "        TARGET=\`basename \$TARGET\`"                                             >> check_source_timestamps.sh
echo    "        rm -f \$TARGET"                                                          >> check_source_timestamps.sh
echo    "        DELETED_STUFF='y'"                                                        >> check_source_timestamps.sh
echo    "    fi"                                                                           >> check_source_timestamps.sh
echo    "done"                                                                             >> check_source_timestamps.sh
echo    "if [ \$DELETED_STUFF ]; then rm -f r64fx; fi"                                    >> check_source_timestamps.sh

chmod u+x check_source_timestamps.sh