######################################################################
# Automatically generated by qmake (3.0) Mon Mar 17 13:51:21 2014
######################################################################

TEMPLATE = app
TARGET = file_dialog_qt
INCLUDEPATH += .

QT += core gui widgets

# Input
SOURCES += file_dialog_qt.cpp
