#include <iostream>
#include <string>

using namespace std;

string num2str(unsigned int num)
{
    if(num < 10)
    {
        return "  " + string(1, (num%10) + 48);
    }

    string str;
    while(num)
    {
        str = string(1, (num%10) + 48) + str;
        num /= 10;
    }

    if(str.size() < 3)
        str = " " + str;

    return str;
}


int main(int argc, char* argv[])
{
    if(argc != 4)
    {
        cerr << "Usage: " << argv[0] << " <Text file to convert to a resource> <Line width> <C++ array name>\n";
        return 1;
    }

    auto path = argv[1];
    FILE* file = fopen(path, "rb");
    if(!file)
    {
        cerr << "Failed to open file \"" << path << "\" !\n";
        return 2;
    }

    int line_width = atoi(argv[2]);
    if(line_width < 0)
    {
        cerr << "Bad line length!\n";
        return 3;
    }

    string text;
    text += "/*\n    Generated from ";
    text += argv[1];
    text += " by tools/build_resource.cpp.\n    Do not edit this file!\n*/\n\n";
    text += "const unsigned char ";
    text += argv[3];
    text += "[] = {";

    unsigned char ch;
    int i = 0;
    int nbytes = 0;
    while(fread(&ch, 1, 1, file) == 1)
    {
        if(i == 0)
        {
            i = line_width;
            text += "\n    ";
        }

        text += num2str(ch);
        text += ", ";

        i--;
        nbytes++;
    }
    text.pop_back();
    text.pop_back();
    text += "\n};\n\n";
    text += "const unsigned long int ";
    text += argv[3];
    text += "_size = ";
    text += num2str(nbytes) + ";\n";

    fclose(file);

    cout << text << "\n";

    return 0;
}