#ifndef R64FX_MACHINE_FLAGS_HPP
#define R64FX_MACHINE_FLAGS_HPP

#define R64FX_MACHINE_DEPLOYED              1
#define R64FX_MACHINE_DEPLOYMENT_PENDING   (1 << 1)
#define R64FX_MACHINE_WITHDRAWAL_PENDING   (1 << 2)
#define R64FX_MACHINE_IS_READY             (1 << 3)
#define R64FX_MACHINE_DATA_MESSAGE_IS_USED (1 << 4)

#endif//R64FX_MACHINE_FLAGS_HPP