#ifndef R64FX_MOUSE_BUTTON_CODES_HPP
#define R64FX_MOUSE_BUTTON_CODES_HPP

#define R64FX_MOUSE_BUTTON_NONE  0
#define R64FX_MOUSE_BUTTON1      1
#define R64FX_MOUSE_BUTTON2      2
#define R64FX_MOUSE_BUTTON3      4
#define R64FX_MOUSE_BUTTON4      8
#define R64FX_MOUSE_BUTTON5     16

#endif//R64FX_MOUSE_BUTTON_CODES_HPP