"#version 130\n"
"\n"
"in vec2 position;\n"
"\n"
"in vec4 color;\n"
"\n"
"/* Scale and shift. */\n"
"uniform vec4 sxsytxty = vec4(1.0, 1.0, 0.0, 0.0);\n"
"\n"
"out vec4 frag_color;\n"
"\n"
"void main()\n"
"{\n"
"    gl_Position = vec4(\n"
"        position.x * sxsytxty[0] + sxsytxty[2],\n"
"        position.y * sxsytxty[1] + sxsytxty[3],\n"
"        0.0,\n"
"        1.0\n"
"    );\n"
"\n"
"    frag_color = color;\n"
"}\n"
"\n"
