"#version 130\n"
"\n"
"in vec2 frag_tex_coord;\n"
"\n"
"uniform vec4 color;\n"
"\n"
"uniform sampler1D sampler;\n"
"\n"
"uniform float gain = 1.0;\n"
"\n"
"void main()\n"
"{\n"
"    vec4 texel = texture(sampler, frag_tex_coord[0]);\n"
"    float min_value = texel[0] * gain;\n"
"    float max_value = texel[1] * gain; \n"
"    float value = frag_tex_coord[1];\n"
"    if(value > min_value && value < max_value)\n"
"    {\n"
"        gl_FragColor = color;\n"
"    }\n"
"    else\n"
"    {\n"
"        discard;\n"
"    }\n"
"}\n"
"\n"
