"#version 130\n"
"\n"
"in vec2 frag_tex_coord;\n"
"\n"
"uniform vec4 color;\n"
"\n"
"uniform sampler2D sampler;\n"
"\n"
"uniform int texture_component;\n"
"\n"
"void main()\n"
"{\n"
"    vec4 texel = texture(sampler, frag_tex_coord);\n"
"\n"
"    gl_FragColor = vec4(\n"
"        color[0],\n"
"        color[1],\n"
"        color[2],\n"
"        1.0 - texel[texture_component]\n"
"    );\n"
"}\n"
"\n"
