"#version 130\n"
"\n"
"in vec2 frag_tex_coord;\n"
"\n"
"uniform int        mode     = 0;\n"
"uniform vec4       color    = vec4(0.0, 0.0, 0.0, 0.0);\n"
"uniform sampler2D  sampler;\n"
"\n"
"void main()\n"
"{\n"
"    vec4 texel = texture(sampler, frag_tex_coord);\n"
"    switch(mode)\n"
"    {\n"
"        //putImage()\n"
"        case 1:\n"
"        {\n"
"            gl_FragColor = vec4(texel[0], texel[0], texel[0], 0.0);\n"
"            break;\n"
"        }\n"
"\n"
"        case 2:\n"
"        {\n"
"            gl_FragColor = vec4(texel[0], texel[0], texel[0], texel[1]);\n"
"            break;\n"
"        }\n"
"\n"
"        case 3:\n"
"        {\n"
"            gl_FragColor = vec4(texel[0], texel[1], texel[2], 0.0);\n"
"            break;\n"
"        }\n"
"\n"
"        case 4:\n"
"        {\n"
"            gl_FragColor = texel;\n"
"            break;\n"
"        }\n"
"\n"
"        //blendColors()\n"
"        case 5:\n"
"        {\n"
"            gl_FragColor = vec4(color[0], color[1], color[2], 1.0 - texel[0]);\n"
"            break;\n"
"        }\n"
"\n"
"        case 6:\n"
"        {\n"
"            gl_FragColor = vec4(color[0], color[1], color[2], 1.0 - texel[1]);\n"
"            break;\n"
"        }\n"
"\n"
"        case 7:\n"
"        {\n"
"            gl_FragColor = vec4(color[0], color[1], color[2], 1.0 - texel[2]);\n"
"            break;\n"
"        }\n"
"\n"
"        case 8:\n"
"        {\n"
"            gl_FragColor = vec4(color[0], color[1], color[2], 1.0 - texel[3]);\n"
"            break;\n"
"        }\n"
"\n"
"        default:\n"
"            discard;\n"
"    }\n"
"}\n"
"\n"
