"#version 130\n"
"\n"
"in vec2 frag_tex_coord;\n"
"\n"
"uniform sampler2D sampler;\n"
"uniform int component_count = 0;\n"
"\n"
"void main()\n"
"{\n"
"    vec4 texel = texture(sampler, frag_tex_coord);\n"
"    switch(component_count)\n"
"    {\n"
"        case 1:\n"
"        {\n"
"            gl_FragColor = vec4(texel[0], texel[0], texel[0], 0.0);\n"
"            break;\n"
"        }\n"
"\n"
"        case 2:\n"
"        {\n"
"            gl_FragColor = vec4(texel[0], texel[0], texel[0], texel[1]);\n"
"            break;\n"
"        }\n"
"\n"
"        case 3:\n"
"        {\n"
"            gl_FragColor = vec4(texel[0], texel[1], texel[2], 0.0);\n"
"            break;\n"
"        }\n"
"\n"
"        case 4:\n"
"        {\n"
"            gl_FragColor = texel;\n"
"            break;\n"
"        }\n"
"\n"
"        default:\n"
"            discard;\n"
"    }\n"
"}\n"
"\n"
