#ifndef R64FX_SIGNAL_NODE_FLAGS_HPP
#define R64FX_SIGNAL_NODE_FLAGS_HPP

#define R64FX_BUILD_IN_PROGRESS  1UL
#define R64FX_NODE_IS_BUILT      2UL
#define R64FX_NODE_UPDATED       4UL

#endif//R64FX_SIGNAL_NODE_FLAGS_HPP
