#ifndef R64FX_THREAD_OBJECT_FLAGS_HPP
#define R64FX_THREAD_OBJECT_FLAGS_HPP

#define R64FX_THREAD_OBJECT_DEPLOYED   1UL
#define R64FX_THREAD_OBJECT_PENDING   (1UL << 1)

#endif//R64FX_THREAD_OBJECT_FLAGS_HPP
