#ifndef R64FX_THREAD_OBJECT_FLAGS_HPP
#define R64FX_THREAD_OBJECT_FLAGS_HPP

#define R64FX_THREAD_OBJECT_DEPLOYED   1UL
#define R64FX_THREAD_OBJECT_PENDING   (1UL << 1)
#define R64FX_THREAD_OBJECT_IS_ROOT   (1UL << 2)

#endif//R64FX_THREAD_OBJECT_FLAGS_HPP
