#ifndef R64FX_WIDGET_FLAGS_HPP
#define R64FX_WIDGET_FLAGS_HPP

/* Values to be used with Widget m_flags. */

#define R64FX_WIDGET_IS_WINDOW               1

#define R64FX_WIDGET_IS_VISIBLE              2
#define R64FX_WIDGET_IS_OBSCURED_LEFT        4
#define R64FX_WIDGET_IS_OBSCURED_TOP         8
#define R64FX_WIDGET_IS_OBSCURED_RIGHT       16
#define R64FX_WIDGET_IS_OBSCURED_BOTTOM      32
#define R64FX_WIDGET_IS_OBSCURED             (4|8|16|32)
#define R64FX_WIDGET_VISIBILITY_FLAGS        (R64FX_WIDGET_IS_VISIBLE | R64FX_WIDGET_IS_OBSCURED)

#define R64FX_WIDGET_OWNS_DATA               64

#define R64FX_WIDGET_WANTS_UPDATE            128
#define R64FX_CHILD_WANTS_UPDATE             256
#define R64FX_WIDGET_UPDATE_FLAGS            (128|256)

#endif//R64FX_WIDGET_FLAGS_HPP